### ISSUE TITLE
Representing traditionally "large" numbers (>= 2^25)

### ISSUE THREAD

**Issue by maxldale** [Mikescher/BefunRep#1]
Reference values:
- A signed 64-bit number has a maximum value of +9,223,372,036,854,775,807 (2^63 - 1)
- A signed 32-bit number has a maximum value of +2,147,483,647 (2^31 - 1)
- For the online interpreter linked on your site the maximum allowed value is +16,777,215 (2^25 - 1) (~0.78% of the biggest signed 32-bit number)

Out of curiosity, is this a limitation of Befunge? What if I wish to represent actual big numbers, with binary representations bigger than 24 bits, or bigger than 32 bits, or bigger than 64 bits? Are these artificial limitations or limitations of the language?

**Comment by Mikescher** [comment]
No, I simply ran BefunRep a while ago for numbers from 0 to 2^24 and uploaded them [here](https://github.com/Mikescher/Befunge_Number_Representations).  
The [online interface](https://mikescher.github.io/Befunge_Number_Representations/) uses the data from there, and thus only works in that range.

You can run BefunRep yourself at least with numbers up to 32bit (not sure for 64bit, it has been a while since I made that :D)

**Comment by maxldale** [comment]
Much appreciated, thank you for the information! (I'll close the issue, but some documentation for clarity might be warranted if you are so inclined)
